import React from "react";
import { Mail, Send, Target } from "lucide-react";
import portrait from "../assets/portrait.webp";
export default function AboutHelp({ui,email}){const en=ui.navAbout==="About";return <section id="about" className="relative px-5"><div className="max-w-6xl mx-auto">
<div className="about-r4-intro reveal"><span>QUALITY VISUALITY · PERSON BEHIND THE SYSTEM</span><h2>{en?"A living practice, not a marketing mask":"Жива практика, а не маркетингова маска"}</h2><p>{en?"After my own path and marketing studies, I am looking for people and projects that need realistic support from the inside out.":"Після власного шляху й навчання маркетингу я шукаю людей і проєкти, яким потрібна реалістична підтримка зсередини й назовні."}</p></div>
<div className="grid lg:grid-cols-[1fr_360px_1fr] gap-8 items-start"><div className="reveal panel p-6"><p className="font-body text-dim leading-relaxed">{en?"I worked in an advertising agency and studied cinematography for film and television at university. I have studied and continue to study psychology and meditation, and I also use Human Design as a reflective language. I bring these directions together in practical marketing.":"Я працював у рекламній агенції та навчався в університеті на оператора кіно і телебачення. Навчався й продовжую вивчати психологію та медитацію, а Human Design використовую як рефлексивну мову. Ці напрямки я поєдную у практичному маркетингу."}</p></div>
<div className="reveal order-first lg:order-none"><div className="relative anim-float"><div className="absolute -inset-3 rounded-2xl" style={{background:"radial-gradient(circle,rgba(230,198,122,.22),transparent 70%)"}}/><div className="relative rounded-2xl overflow-hidden" style={{border:"1px solid rgba(230,198,122,.35)",boxShadow:"0 20px 60px rgba(0,0,0,.6)"}}><img src={portrait} alt="Quality Visuality" className="w-full block"/></div></div></div>
<div className="reveal panel p-6"><Target size={20} className="text-gold mb-3"/><p className="font-body text-dim leading-relaxed">{en?"With me, you can move from first clarity toward a system that works and fits your individual practice — whether that practice takes the form of a business, a personal brand or a project still finding its form.":"Зі мною ти можеш пройти шлях від першої ясності до системи, яка працює й відповідає саме твоїй індивідуальній практиці — чи проявляється вона як бізнес, особистий бренд або проєкт, що лише знаходить свою форму."}</p><p className="font-body text-dim leading-relaxed mt-4">{en?"I don't give excess tools or empty promises. Everything has its place and its time.":"Не даю зайвих інструментів і порожніх обіцянок. Усьому є своє місце і свій час."}</p></div></div>
<div id="contact" className="panel panel-glow mt-8 p-8 md:p-10 text-center reveal relative overflow-hidden"><div className="relative"><Send size={30} className="text-gold mx-auto mb-4"/><h3 className="font-display gold-gradient-text mb-2" style={{fontSize:"clamp(22px,3.4vw,34px)",fontWeight:800}}>{en?"Describe your situation. We'll look for your next personal step.":"Опиши свою ситуацію. Пошукаємо твій наступний особистий крок."}</h3><p className="font-body text-dim mb-6 max-w-2xl mx-auto">{en?"No verdicts about what is right or wrong — we look at what is alive, what already works and what needs attention now.":"Без оцінок «правильно / неправильно» — дивимось, що живе, що вже працює і що зараз потребує уваги."}</p><a href={`mailto:${email}`} className="btn-gold inline-flex items-center gap-2 px-7 py-3.5"><Mail size={18}/>{en?"Describe my situation":"Описати свою ситуацію"}</a></div></div>
</div></section>}
