import React, { useState } from "react";
import { Droplets, Leaf, Flame, HeartHandshake, Settings2, ArrowRight, Mail } from "lucide-react";
import "./ExperienceUX.css";
const PATHS=[
{id:"water",icon:Droplets,color:"#65b8ff",ua:{label:"Хочу ясності",title:"Вода · ясність",question:"Що зараз справді потребує твоєї уваги?",next:"Починаємо з твоєї ситуації: сенс, людина, практика, продукт і вихідна точка."},en:{label:"I want clarity",title:"Water · clarity",question:"What truly needs your attention now?",next:"We begin with your situation: meaning, person, practice, product and starting point."}},
{id:"wood",icon:Leaf,color:"#83cf8b",ua:{label:"Шукаю напрям",title:"Дерево · напрям",question:"Де для тебе є простір природного росту?",next:"Дивимось на людей, середовище, попит, сусідів у ніші й позиціонування."},en:{label:"I seek direction",title:"Wood · direction",question:"Where is there natural room for you to grow?",next:"We look at people, context, demand, neighbours in the niche and positioning."}},
{id:"fire",icon:Flame,color:"#ff9459",ua:{label:"Хочу проявитися",title:"Вогонь · прояв",question:"Який прояв зараз підтримає твій наступний крок?",next:"Знаходимо достатню форму прояву: історія, контент, канал, запуск або трафік."},en:{label:"I want visibility",title:"Fire · expression",question:"What expression supports your next step now?",next:"We find a sufficient form: story, content, channel, launch or traffic."}},
{id:"earth",icon:HeartHandshake,color:"#e6b35f",ua:{label:"Хочу втілити",title:"Земля · втілення",question:"Як дати сенсу форму, яку людина може відчути?",next:"Збираємо досвід: сайт, візуальна мова, фото, відео, UX і шлях людини."},en:{label:"I want embodiment",title:"Earth · embodiment",question:"How can meaning take a form people can feel?",next:"We shape the experience: website, visual language, photo, video, UX and journey."}},
{id:"metal",icon:Settings2,color:"#c9d5e6",ua:{label:"Хочу систему",title:"Метал · система",question:"Що вже працює і що варто підсилити?",next:"Прибираємо зайве, вимірюємо, структуруємо й автоматизуємо лише там, де це служить практиці."},en:{label:"I want a system",title:"Metal · system",question:"What already works and deserves strengthening?",next:"We remove excess, measure, structure and automate only where it serves the practice."}}
];
export default function ClarityNavigator({lang="ua"}){const[active,setActive]=useState("water");const current=PATHS.find(x=>x.id===active)||PATHS[0];const c=current[lang]||current.ua;const ua=lang==="ua";return <section id="clarity" className="clarity-section"><div className="max-w-6xl mx-auto px-5">
<div className="clarity-heading reveal"><span className="clarity-eyebrow">QUALITY VISUALITY · YOUR NEXT STEP</span><h2>{ua?"Набридло шукати один універсальний крок, який нібито має запустити все одразу?":"Tired of searching for one universal step that is supposed to make everything work at once?"}</h2><p>{ua?"Твоєму проєкту не потрібен весь маркетинг одразу. Тобі потрібен наступний індивідуальний крок — той, що відповідає саме твоїй ситуації зараз.":"Your project does not need all of marketing at once. You need the next individual step — one that fits your situation now."}</p><p className="clarity-principle">{ua?"Починаємо з твоєї ситуації. Не продаю зайвого. Коригуємо шлях разом. Не даю зайвих інструментів і порожніх обіцянок. Усьому є своє місце і свій час.":"We begin with your situation. I don't sell what you don't need. We adjust the path together. No excess tools or empty promises. Everything has its place and its time."}</p></div>
<div className="clarity-tabs reveal" role="tablist">{PATHS.map(p=>{const Icon=p.icon,text=p[lang]||p.ua;return <button key={p.id} role="tab" aria-selected={active===p.id} className={`clarity-tab ${active===p.id?"is-active":""}`} style={{"--path-color":p.color}} onClick={()=>setActive(p.id)}><span className="clarity-tab-icon"><Icon size={18}/></span><span>{text.label}</span></button>})}</div>
<div className="clarity-result panel reveal" style={{"--path-color":current.color}}><div className="clarity-result-main"><span className="clarity-result-kicker">{c.title}</span><h3>{c.question}</h3><p>{c.next}</p></div><div className="clarity-result-actions"><a href="#dao" className="clarity-primary">{ua?"Побачити шлях":"See the path"}<ArrowRight size={16}/></a><a href="mailto:qualityvisuality@gmail.com" className="clarity-secondary"><Mail size={15}/>{ua?"Описати ситуацію":"Describe my situation"}</a></div></div>
</div></section>}
