import React from "react";
import { Camera, Eye, PenTool, Layers3, Compass, ArrowUpRight, Mail, Sparkles } from "lucide-react";
import "./QualityVisualityEnhancements.css";

const PRODUCTS=[
 {id:"content",icon:PenTool,tag:"ІНСТРУМЕНТ · КОНТЕНТ",title:"Контент без шуму",desc:"Створення контенту починається із задачі бізнесу: визначаємо ситуацію → створюємо рішення → перевіряємо результат.",blocks:["визначення задачі бізнесу","контент-архітектура та формати","сценарії, тексти й візуал"],arch:"Сенс → повідомлення → увага → дія",print:"lines",color:"#c9a85d"},
 {id:"photo",icon:Camera,tag:"12 ТИЖНІВ · ФОТОГРАФІЯ",title:"Фотографія як інструмент людини",desc:"Фотографія + психологія + робота з тілом і мисленням: через камеру вчимося уважніше бачити себе, простір і світ.",blocks:["Психіка, тіло та розум","Фотографічна майстерність: база, якої навчають в університетах і курсах","Практика — 12 тижнів, 1 тема щотижня"],arch:"6 архетипів: Дослідник · Природність · Експеримент · Контакт · Проєкція · Перспектива",print:"lens",color:"#dcae5b"},
 {id:"focus",icon:Eye,tag:"АВТОРСЬКИЙ КУРС",title:"Фокус уваги",desc:"Авторський курс з фокусу уваги через мандало-терапію, сакральну геометрію та практики спостереження.",blocks:["мандало-терапія","сакральна геометрія","увага як ресурс для творчості та роботи"],arch:"6 ліній Human Design як архетипи способу дивитися",print:"mandala",color:"#70b6e8"},
 {id:"water",icon:Sparkles,tag:"ВОДА · ЗАГЛИБЛЕННЯ",title:"Курс",desc:"Спіритуальна консультація для заземлення, бази й яснішого відчуття, куди рухатися далі.",blocks:["базове торкання Human Design: тип, стратегія, авторитет","Матриця Долі","Архетипи Таро","відповіді на заглиблені питання"],arch:"Сценарії проявлення у житті · стосунки · цілісна взаємодія із собою",print:"stars",color:"#65b8ff"},
 {id:"support",icon:Layers3,tag:"КОМПЛЕКСНА ПІДТРИМКА",title:"Етичний маркетинг · комплексний курс",desc:"Повний маршрут із комплексною підтримкою: від пошуку сенсу до дій, втілення та систематизації маркетингу.",blocks:["Вода — знаходимо сенс","Дерево — встановлюємо напрям","Вогонь — переходимо до дії","Земля — втілюємо та будуємо взаємодію","Метал — систематизуємо"],arch:"Один маршрут · підтримка · інструменти під конкретну задачу",print:"orbit",color:"#efc36d"},
 {id:"tools",icon:Compass,tag:"П'ЯТИЙ ЕЛЕМЕНТ · ОКРЕМО",title:"Інструменти та напрями",desc:"Будь-який окремий інструмент можна придбати самостійно під конкретну ситуацію бізнесу — без проходження всього маршруту.",blocks:["визначаємо задачу","створюємо рішення","обираємо конкретний інструмент","перевіряємо результат"],arch:"Окремий інструмент або частина комплексної системи",print:"grid",color:"#c9d5e6"},
];
function Print({type,color}){return <div className={`product-print print-${type}`} style={{"--print-color":color}} aria-hidden="true"><span/><span/><span/><span/><span/></div>}
export default function Courses({lang="ua"}){return <section id="courses" className="courses-section"><div className="max-w-6xl mx-auto px-5"><div className="section-heading reveal"><span className="diamond"/><div><div className="section-kicker">QUALITY VISUALITY · LEARNING</div><h2>{lang==="ua"?"АВТОРСЬКІ ПРОДУКТИ":"AUTHOR PRODUCTS"}</h2><p>{lang==="ua"?"Ці продукти можна проходити окремо або зібрати в комплексну підтримку етичного маркетингу.":"Use a product on its own or build a complete ethical marketing support system."}</p></div><span className="diamond"/></div><div className="product-intro panel reveal"><strong>Комплексний курс з комплексною підтримкою етичного маркетингу</strong><p>Від <b>Води</b>, де ми знаходимо сенс, через <b>Дерево</b> і <b>Вогонь</b> до дії, через <b>Землю</b> — втілення, спілкування і взаємодію — та до <b>Металу</b>, де все систематизується.</p></div><div className="course-grid">{PRODUCTS.map((c,i)=>{const Icon=c.icon;return <article className={`course-card panel reveal product-${c.id}`} key={c.id} style={{"--course-color":c.color,animationDelay:`${i*.06}s`}}><Print type={c.print} color={c.color}/><div className="course-top"><span className="course-icon"><Icon size={22}/></span><span className="course-tag">{c.tag}</span></div><h3>{c.title}</h3><p className="course-desc">{c.desc}</p><div className="course-blocks">{c.blocks.map(x=><span key={x}>✓ {x}</span>)}</div><div className="course-arch"><small>АРХЕТИПИ / ЛОГІКА</small><p>{c.arch}</p></div><a className="course-cta" href={`mailto:qualityvisuality@gmail.com?subject=${encodeURIComponent("Quality Visuality · "+c.title)}`}><Mail size={15}/>{lang==="ua"?"Дізнатись цінність":"Discover the value"}<ArrowUpRight size={15}/></a></article>})}</div></div></section>}
