import React from "react";
import { Camera, Eye, Gem, ArrowUpRight, Mail } from "lucide-react";

const COURSES=[
 {id:"photo",icon:Camera,tag:"12 ТИЖНІВ · ФОТОГРАФІЯ",title:"Фотографія як інструмент людини",desc:"Фотографія + психологія + робота з тілом і мисленням: через камеру вчимося уважніше бачити себе, простір і світ.",blocks:["Психіка, тіло та розум","Фотографічна майстерність: база","Практика — 12 тижнів, 1 тема щотижня"],arch:"6 архетипів: Дослідник · Природність · Експеримент · Контакт · Проєкція · Перспектива",color:"#dcae5b"},
 {id:"focus",icon:Eye,tag:"АВТОРСЬКИЙ КУРС",title:"Фокус уваги",desc:"Тренування уваги через мандали та спостереження: не додавати більше інформації, а бачити точніше.",blocks:["Мандали як інструмент фокусу","Практики спостереження","Увага як ресурс для творчості та роботи"],arch:"6 ліній Human Design як архетипи способу дивитися",color:"#70b6e8"},
 {id:"amber",icon:Gem,tag:"СТРАТЕГІЧНИЙ АВТОРСЬКИЙ КУРС",title:"Янтар · архетипи шляху",desc:"Концептуальна карта самопізнання, що поєднує архетипи Human Design та Матриці Долі як мову для розгляду запиту.",blocks:["архетипи Human Design","Матриця Долі","сценарії проявлення, стосунків і роботи"],arch:"Не передбачення, а інструмент рефлексії та вибору наступного кроку",color:"#efc36d"},
];

export default function Courses({lang="ua"}){return <section id="courses" className="courses-section"><div className="max-w-6xl mx-auto px-5"><div className="section-heading reveal"><span className="diamond"/><div><div className="section-kicker">QUALITY VISUALITY · LEARNING</div><h2>{lang==="ua"?"АВТОРСЬКІ ПРОДУКТИ":"AUTHOR PRODUCTS"}</h2><p>{lang==="ua"?"Не просто курс. Практичний маршрут, який можна пройти у своєму темпі.":"Not just a course. A practical route you can take at your own pace."}</p></div><span className="diamond"/></div><div className="course-grid">{COURSES.map((c,i)=>{const Icon=c.icon;return <article className="course-card panel reveal" key={c.id} style={{"--course-color":c.color,animationDelay:`${i*.1}s`}}><div className="course-top"><span className="course-icon"><Icon size={22}/></span><span className="course-tag">{c.tag}</span></div><h3>{c.title}</h3><p className="course-desc">{c.desc}</p><div className="course-blocks">{c.blocks.map(x=><span key={x}>✓ {x}</span>)}</div><div className="course-arch"><small>АРХЕТИПИ</small><p>{c.arch}</p></div><a className="course-cta" href={`mailto:qualityvisuality@gmail.com?subject=${encodeURIComponent("Quality Visuality · "+c.title)}`}><Mail size={15}/>{lang==="ua"?"Дізнатись цінність":"Discover the value"}<ArrowUpRight size={15}/></a></article>})}</div></div></section>}
