import React from"react";
import{Camera,Eye,Compass,Layers3,Waves,Mail,ArrowUpRight,Gift,Clock3}from"lucide-react";
import"./R5Experience.css";
const MAIL=(subject)=>`mailto:qualityvisuality@gmail.com?subject=${encodeURIComponent(subject)}`;
export default function CoursesR5(){return <section id="courses" className="r5-products"><div className="r5-products-wrap"><div className="r5-products-head"><div className="eyebrow">QUALITY VISUALITY · PRODUCTS</div><h2>АВТОРСЬКІ ПРОДУКТИ Й ФОРМАТИ РОБОТИ</h2><p>Можна зайти через курс, окремий інструмент, один етап або пройти весь цикл. Без примусу купувати більше, ніж реально потрібно задачі.</p></div><div className="r5-free-call"><div><strong>30 хвилин — безкоштовна консультація</strong><p>Щоб зрозуміти задачу, стартову точку і який формат роботи справді доречний.</p></div><a className="r5-mail-btn" href={MAIL("Quality Visuality · Безкоштовна 30-хв консультація")}><Clock3 size={14}/>Записатись<ArrowUpRight size={13}/></a></div><div className="r5-product-grid">
<article className="r5-product r5-product-photo" style={{"--p":"#dcae5b"}}><div className="tag">12 ТИЖНІВ · ВІДЕОКУРС</div><h3>Фотографія як інструмент людини</h3><p>Фотографія + психологія + робота з тілом і мисленням. Через камеру вчимося уважніше бачити себе, простір і світ.</p><div className="r5-bullets"><span>✓ психіка, тіло та розум</span><span>✓ фотографічна майстерність</span><span>✓ 12 тижнів практики — одна тема щотижня</span></div><div className="r5-product-actions"><a className="r5-mail-btn" href={MAIL("Quality Visuality · Фотографія як інструмент людини")}><Mail size={13}/>Дізнатись цінність</a></div></article>
<article className="r5-product r5-product-focus" style={{"--p":"#70b6e8"}}><div className="tag">ВІДЕОКУРС · УВАГА</div><h3>Фокус уваги</h3><p>Мандали, сакральна геометрія та практики спостереження. Вчимося бачити, де знаходиться увага і як повертати її до того, що справді важливо.</p><div className="r5-chips"><span className="r5-chip">мандали</span><span className="r5-chip">сакральна геометрія</span><span className="r5-chip">спостереження</span><span className="r5-chip">фокус</span></div><div className="r5-product-actions"><a className="r5-mail-btn" href={MAIL("Quality Visuality · Фокус уваги")}><Mail size={13}/>Дізнатись цінність</a></div></article>
<article className="r5-product r5-product-session" style={{"--p":"#65b8ff"}}><div className="tag">СЕСІЯ · ЗАГЛИБЛЕННЯ</div><h3>Сесія зі мною · заглиблення у вас як особистість</h3><p><b>Що вирішує?</b> Дає більше розуміння вам про вас. Це окремий простір, де працюємо за вашим запитом: не навколо симптома, а ближче до кореня питання.</p><div className="r5-bullets"><span>✓ тип, стратегія та внутрішній авторитет</span><span>✓ життєвий шлях і напрям руху</span><span>✓ стосунки та проявлення у роботі</span><span>✓ внутрішня опора, саморегуляція, конкретні дії й практики</span></div><div className="r5-chips"><span className="r5-chip">Human Design</span><span className="r5-chip">Таро</span><span className="r5-chip">Астрологія</span><span className="r5-chip">Матриця Долі</span><span className="r5-chip">мінерали сили</span><span className="r5-chip">місця сили</span></div><div className="r5-gift"><Gift size={12}/> При вході у комплексний маркетинговий супровід частина сесії про вас — у дар.</div><div className="r5-product-actions"><a className="r5-mail-btn" href={MAIL("Quality Visuality · Сесія із заглиблення")}><Waves size={13}/>Дізнатись цінність</a></div></article>
<article className="r5-product" style={{"--p":"#c9d5e6"}}><div className="tag">ОКРЕМО · ІНСТРУМЕНТ</div><h3>Взяти тільки те, що потрібно зараз</h3><p>Окремий модуль без пакету. Формулюємо задачу, визначаємо метрику, робимо рішення і перевіряємо результат.</p><div className="r5-tool-list">{["Підготовка до просування","Аналіз конкурентів","Аналіз ніші","SMM","Фотоконтент","Відеоконтент","Сайти та лендинги","Web-аналітика","Воронки","CRO","Таргет","Google Ads","SEO","Email / Push","YouTube","AI-автоматизація"].map(x=><span key={x}>{x}</span>)}</div><div className="r5-product-actions"><a className="r5-mail-btn" href={MAIL("Quality Visuality · Окремий маркетинговий інструмент")}><Compass size={13}/>Обрати інструмент</a><a className="r5-ghost-link" href="#tools">Переглянути всі інструменти <ArrowUpRight size={12}/></a></div></article>
<article className="r5-product" style={{"--p":"#83cf8b"}}><div className="tag">ОКРЕМО · ЦІЛИЙ ЕТАП</div><h3>Не один інструмент, а один повний етап</h3><p>Коли фундамент уже є, але потрібна глибока робота тільки в одному секторі системи.</p><div className="r5-stage-list"><div className="r5-stage-mini"><b>Вода</b><small>продукт, сенс, питання, ясність</small></div><div className="r5-stage-mini"><b>Дерево</b><small>ринок, конкуренти, ніша, напрям</small></div><div className="r5-stage-mini"><b>Вогонь</b><small>стратегія прояву, SMM, запуск</small></div><div className="r5-stage-mini"><b>Земля</b><small>сайт, UX, контент, досвід</small></div><div className="r5-stage-mini"><b>Метал</b><small>аналітика, funnel, CRO, automation</small></div></div><div className="r5-gift"><Gift size={12}/> Якщо обираєте Дерево, Вогонь, Землю або Метал — базове заглиблення Води входить у роботу як подарунок.</div><div className="r5-product-actions"><a className="r5-mail-btn" href={MAIL("Quality Visuality · Окремий етап маркетингу")}><Mail size={13}/>Дізнатись цінність етапу</a></div></article>
<article className="r5-product r5-product-full" style={{"--p":"#efc36d"}}><div className="tag">КОМПЛЕКСНЕ ВЕДЕННЯ · ВІД ПОЧАТКУ ДО КІНЦЯ</div><h3>Вода → Дерево → Вогонь → Земля → Метал</h3><p>Повний маршрут: від сенсу й дослідження до прояву, втілення, системи, вимірювання та наступного циклу. Інструменти підбираються не за модою, а за реальною задачею бренду.</p><div className="r5-stage-list"><div className="r5-stage-mini"><b>01 · Вода</b><small>заглиблюємось</small></div><div className="r5-stage-mini"><b>02 · Дерево</b><small>обираємо напрям</small></div><div className="r5-stage-mini"><b>03 · Вогонь</b><small>проявляємо</small></div><div className="r5-stage-mini"><b>04 · Земля</b><small>втілюємо</small></div><div className="r5-stage-mini"><b>05 · Метал</b><small>систематизуємо</small></div></div><div className="r5-product-actions"><a className="r5-mail-btn" href={MAIL("Quality Visuality · Комплексне ведення")}><Layers3 size={13}/>Дізнатись цінність</a></div></article>
</div></div></section>}
