import React from "react";
import { ArrowDown, Droplets, Leaf, Flame, Mountain, CircleDot, ArrowUpRight } from "lucide-react";
import { ELEMENT_SYSTEM } from "../constants/elementSystem";
import { toolsForElement } from "../constants/toolCatalog";
import "./ProductArt.css";
import "./RevisionR4.css";
const ICONS={water:Droplets,wood:Leaf,fire:Flame,earth:Mountain,metal:CircleDot};
const ORDER=["water","wood","fire","earth","metal"];
export default function DaoSense({lang="ua",onOpen}){const isUa=lang==="ua";const openElement=id=>{const element=ELEMENT_SYSTEM[id],text=element[lang]||element.ua,tools=toolsForElement(id);onOpen?.({id,sound:id,name:text.name,color:element.color,kicker:`5 ELEMENTS · ${text.phase}`,essence:`${text.question} → ${text.outcome}`,points:text.clientQuestions,valueTitle:isUa?"ДЕ І ЯКІ ПИТАННЯ ВИРІШУЄМО":"WHERE THIS HELPS",value:text.summary,deliver:tools.map(t=>(t[lang]||t.ua).name),offers:tools.map(t=>(t[lang]||t.ua).name),cases:text.cases})};return <section id="dao" className="dao-section"><div className="max-w-6xl mx-auto px-5"><div className="dao-heading reveal"><span className="diamond"/><div><div className="dao-kicker">DAO · WU XING · 5 ELEMENTS</div><h2>LESS IS MORE</h2><p>{isUa?"Не додавати шум. Прибрати зайве — і побачити, що вже працює. Натисни на елемент: побачиш 3 клієнтські кейси, питання та всі інструменти цього етапу.":"Don't add noise. Remove the excess and see what already works. Open an element for three client cases, questions and every tool in that stage."}</p></div><span className="diamond"/></div><div className="dao-grid">{ORDER.map((id,i)=>{const item=ELEMENT_SYSTEM[id],Icon=ICONS[id],t=item[lang]||item.ua;return <button type="button" key={id} className={`dao-item dao-${id} reveal dao-clickable`} style={{animationDelay:`${i*.08}s`,"--dao-color":item.color}} onClick={()=>openElement(id)}><div className="dao-icon" style={{color:item.color,borderColor:`${item.color}55`,boxShadow:`0 0 30px ${item.color}16`}}><Icon size={22}/></div><div><div className="dao-name" style={{color:item.color}}>{t.name}</div><div className="dao-sub">{t.outcome}</div><p>{t.question} {t.summary.split(".")[0]}.</p><span className="dao-open">{isUa?"Відкрити логіку":"Open logic"}<ArrowUpRight size={12}/></span></div></button>})}</div><div className="tea-pour reveal"><div className="tea-board" aria-hidden="true"><i/><i/><i/><i/></div><div className="tea-scene" aria-label={isUa?"Реалістична чайна сцена":"Realistic tea scene"}><div className="tea-steam"><i/><i/><i/><i/></div><div className="tea-pot" aria-label={isUa?"Китайський чайник":"Chinese teapot"}><span className="tea-lid"/><span className="tea-body"/><span className="tea-handle"/><span className="tea-spout"/><span className="tea-clay-mark"/><span className="tea-highlight"/></div><span className="tea-stream"/><div className="tea-cup"><span className="tea-liquid"/><span className="tea-cup-shine"/></div><span className="tea-reflection"/></div><div className="tea-copy"><span>下一泡 · NEXT POUR</span><strong>{isUa?"Додаємо ще води для наступного проливу":"Add more water for the next pour"}</strong><p>{isUa?"Цикл не закінчується. Нові дані повертають нас до Води — але вже на іншій глибині.":"The cycle doesn't end. New data returns us to Water at a different depth."}</p><a href="#clarity"><ArrowDown size={15}/>{isUa?"Далі — знайти свою точку":"Next — find your starting point"}</a></div></div></div></section>}
