import React, { useEffect, useMemo, useRef, useState } from "react";
import teaScene from "../assets/tea-scroll-scene.webp";
import "./ScrollCinematics.css";
const clamp=v=>Math.min(1,Math.max(0,v));
export default function TeaScrollScene({lang="ua"}){const rootRef=useRef(null);const[progress,setProgress]=useState(0);const ua=lang==="ua";
useEffect(()=>{let raf=0;const update=()=>{raf=0;const n=rootRef.current;if(!n)return;const r=n.getBoundingClientRect(),travel=Math.max(n.offsetHeight-window.innerHeight,1);setProgress(clamp(-r.top/travel))};const req=()=>{if(!raf)raf=requestAnimationFrame(update)};update();window.addEventListener("scroll",req,{passive:true});window.addEventListener("resize",req);return()=>{if(raf)cancelAnimationFrame(raf);window.removeEventListener("scroll",req);window.removeEventListener("resize",req)}},[]);
const style=useMemo(()=>{const fill=clamp((progress-.28)/.4),streamIn=clamp((progress-.22)/.12),streamOut=1-clamp((progress-.7)/.1);return{"--tea-progress":progress,"--tea-zoom":1.025+progress*.018,"--tea-fill":fill,"--tea-steam-opacity":.16+fill*.58,"--tea-stream":streamIn*streamOut,"--tea-copy-change":clamp((progress-.66)/.16)}},[progress]);
const stage=progress<.34?0:progress<.68?1:2;const copy=ua?[
["Перший пролив","Спершу стає цікаво.","Не все потрібно зрозуміти одразу. Увага вже змінює те, що ти бачиш."],
["Другий пролив","З другої чашки — ясніше.","Те саме листя розкривається інакше. Так само й проєкт, коли дивишся на нього з нової точки."],
["Третій пролив","З третьої — проступає система.","Наступний пролив розкриває історію чаю по-іншому. Сенс не нав’язується — він дозріває разом зі шляхом."]]:[
["First pour","First, curiosity appears.","Not everything needs to be understood at once. Attention already changes what you see."],
["Second pour","With the second cup, it becomes clearer.","The same leaves unfold differently. A project does too when seen from a new point."],
["Third pour","With the third, a system emerges.","The next pour tells the tea's story differently. Meaning is not imposed; it matures with the journey."]];
return <div ref={rootRef} className="tea-scroll-chapter" style={style}><div className="tea-scroll-sticky"><div className="tea-scroll-frame"><img className="tea-scroll-photo" src={teaScene} alt={ua?"Гунфу-чай: третя чашка поступово наповнюється чаєм":"Gongfu tea: the third cup gradually fills with tea"}/><div className="tea-scroll-grade" aria-hidden="true"/><span className="tea-scroll-stream" aria-hidden="true"><i/></span><span className="tea-scroll-fill" aria-hidden="true"><i/><b/></span><span className="tea-scroll-steam steam-one" aria-hidden="true"/><span className="tea-scroll-steam steam-two" aria-hidden="true"/><div className="tea-scroll-copy" aria-live="polite"><div className="tea-copy-state tea-copy-journey"><span>功夫茶 · GONGFU CHA · WATER</span><strong>{copy[stage][1]}</strong><p>{copy[stage][2]}</p><small>{copy[stage][0]} · {stage+1}/3</small></div></div><div className="tea-scroll-meter" aria-hidden="true"><span style={{height:`${progress*100}%`}}/><b>SCROLL · POUR</b></div></div></div></div>}
