import React from "react";
import { X, ArrowRight, MessageCircle, CheckCircle2, GraduationCap, Sparkles } from "lucide-react";

const DETAILS={
 "Сайти та лендинги":{title:"Сайт / лендинг",promise:"Не просто сторінка, а зрозумілий маршрут від першого враження до потрібної дії.",how:["визначаємо задачу сайту і цільову дію","будуємо структуру та customer journey","створюємо тексти, візуал і UX","підключаємо аналітику, SEO-базу та перевіряємо конверсії"],result:"Готовий сайт або лендинг з логічною структурою, CTA, аналітикою та можливістю далі оптимізувати його.",case:"Людина заходить на сторінку й одразу розуміє: для кого це, яка цінність, що робити далі."},
 "Websites & landing pages":{title:"Website / landing page",promise:"Not just a page, but a clear route from first impression to the desired action.",how:["define the task and primary action","build structure and customer journey","create copy, visual system and UX","connect analytics, SEO basics and validate conversion"],result:"A working website or landing page with clear CTAs, analytics and room for optimization.",case:"A visitor immediately understands who it is for, why it matters and what to do next."},
 "Створення фотоконтенту":{title:"Фотоконтент",promise:"Візуальне рішення під конкретну задачу бізнесу — не просто красиві кадри.",how:["визначаємо роль фото у воронці","формуємо референси, shot-list і сценарій","створюємо або куруємо матеріал","адаптуємо під сайт, SMM та рекламу"],result:"Серія матеріалів, яку можна реально використати в комунікації й продажах.",case:"Один фотодень → візуальна бібліотека для лендингу, соцмереж і рекламних креативів.",course:"12-тижневий фотокурс"},
 "Photo content":{title:"Photo content",promise:"A visual solution for a concrete business task — not beautiful images for their own sake.",how:["define the role of photography","build references and shot-list","create or curate the material","adapt for web, social and ads"],result:"A reusable visual library for real communication tasks.",case:"One photo production → assets for landing page, social and ads.",course:"12-week photography course"},
 "Контент-маркетинг":{title:"Контент-маркетинг",promise:"Контент як система довіри, а не нескінченна гонка за охопленнями.",how:["визначаємо задачу","будуємо контент-архітектуру","створюємо формати та сценарії","дивимось на метрики й коригуємо"],result:"Контентна система, яку команда може повторювати без щоденного винаходження себе заново.",case:"Замість хаотичної стрічки — кілька зрозумілих форматів, пов'язаних з продуктом і customer journey."},
 "SMM":{title:"SMM",promise:"Соцмережі як продовження бренду, а не фабрика випадкових постів.",how:["контент-архітектура","рубрики та сценарії","контент-план і виробництво","аналітика й оптимізація"],result:"Система присутності у соцмережах: теми, формати, ритм і метрики.",case:"SMM перестає існувати окремо від сайту, продукту й воронки."},
 "Web-аналітика":{title:"Web-аналітика",promise:"Поведінка людей перетворюється на рішення.",how:["налаштовуємо події та конверсії","будуємо воронку","створюємо дашборд","формуємо гіпотези для покращення"],result:"Видно, звідки приходять люди, де губляться і що варто змінювати.",case:"Замість відчуття «сайт не працює» — конкретний етап воронки та вимірювана гіпотеза."},
 "Воронки":{title:"Воронка продажів",promise:"Шлях від першого контакту до рішення про купівлю конкретного продукту, курсу чи послуги.",how:["customer journey","контент / лід-магніт / офер","лендинг і точки конверсії","email / messenger / remarketing"],result:"Карта воронки + потрібні матеріали й точки вимірювання.",case:"Для одного курсу збираємо окремий маршрут: контент → сторінка → заявка → прогрів → продаж."},
 "Funnels":{title:"Sales funnel",promise:"A route from first contact to a decision around one concrete product or course.",how:["customer journey","content / lead magnet / offer","landing and conversion points","email / messenger / remarketing"],result:"A funnel map, assets and measurement points.",case:"One course gets its own clear path from discovery to purchase."},
 "Conversion Rate Optimization":{title:"Conversion Rate Optimization",promise:"Знаходимо, де люди губляться, і тестуємо, що допомагає їм рухатися далі.",how:["аналіз поведінки","UX-аудит сторінки","список гіпотез за пріоритетом","A/B-тести та вимірювання"],result:"CRO-roadmap: що змінювати спочатку, навіщо і якою метрикою перевіряти.",case:"Не «зробити кнопку яскравішою», а знайти реальну фрикцію і перевірити зміни даними."},
 "Підготовка до просування":{title:"Підготовка до просування",promise:"Перед рекламою прибираємо те, що змушує бюджет працювати проти бізнесу.",how:["офер і позиціонування","аудиторія та конкуренти","KPI і точки конверсії","креативи та запуск"],result:"Чітке рішення, що саме просувати, кому, куди вести й що вимірювати."},
 "Аналіз конкурентів":{title:"Аналіз конкурентів",promise:"Не копіювати ринок — побачити вільний простір.",how:["карта конкурентів","продукти, офери та комунікації","контентні та рекламні патерни","можливості диференціації"],result:"Документ з картою ринку, можливостями й напрямом позиціонування."},
 "Таргетована реклама":{title:"Таргетована реклама",promise:"Платний трафік там, де є сенс його купувати.",how:["сегментація","креативні гіпотези","кампанії","оптимізація за KPI"],result:"Кампанія + аналітика + зрозумілий критерій, коли масштабувати, а коли зупиняти."},
 "Google Ads":{title:"Google Ads",promise:"Працюємо з попитом, який уже сформувався, і вимірюємо результат.",how:["семантика","структура кампаній","оголошення","аналітика та оптимізація"],result:"Структурована search-кампанія, пов'язана з реальною сторінкою і конверсією."},
 "AI етична автоматизація":{title:"Етичний AI",promise:"Автоматизація рутини так, щоб технологія залишалася інструментом людини.",how:["знаходимо повторювані задачі","проєктуємо AI-процес","автоматизуємо","контролюємо якість і людський тон"],result:"Менше ручної рутини без передачі машині відповідальності за сенс і фінальне рішення."},
 "SEO":{title:"SEO",promise:"Сайт зрозумілий людям і пошуковим системам.",how:["семантика","структура сторінок","технічне SEO","контент і перелінковка"],result:"SEO-roadmap і базова оптимізація сайту під реальні пошукові наміри."},
 "Email-маркетинг & Push":{title:"Email & Push",promise:"Повертати людину до бренду доречно, а не переслідувати.",how:["сегментація","ланцюжки","автоматизація","тестування"],result:"Сценарії комунікації для onboarding, прогріву, retention або повторної покупки."},
 "YouTube":{title:"YouTube",promise:"Відео як медіа-актив бренду.",how:["позиціонування каналу","контентні серії","сценарії","аналітика утримання"],result:"Контентна система каналу, а не список випадкових тем."},
 "Створення відеоконтенту":{title:"Відеоконтент",promise:"Кадр, звук і історія працюють на одну думку.",how:["концепція","сценарій","зйомка / монтаж","адаптації під канали"],result:"Відеоматеріали під конкретні touchpoints бренду."},
 "Цифрові знання":{title:"Цифрові знання",promise:"Карта digital-маркетингу, щоб інструменти перестали виглядати випадковим набором.",how:["визначаємо контекст","розкладаємо канали","визначаємо пріоритети","обираємо наступний крок"],result:"Ясність, що потрібно саме зараз, а що можна не робити."}
};

export default function ToolModal({tool,lang="ua",onClose}){
 const isUa=lang==="ua";const d=DETAILS[tool]||{title:tool,promise:isUa?"Окремий інструмент під конкретну задачу.":"A standalone tool for a concrete task.",how:isUa?["визначаємо задачу","обираємо метрику","створюємо рішення","вимірюємо результат"]:["define the task","choose the metric","create the solution","measure the result"],result:isUa?"Результат і формат визначаємо під задачу.":"Result and format are defined around the task."};
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background:"rgba(3,5,10,.9)",backdropFilter:"blur(9px)"}} onClick={onClose}><div className="panel panel-glow tool-modal reveal in" onClick={e=>e.stopPropagation()}><button onClick={onClose} className="btn-ghost absolute right-4 top-4 w-10 h-10 flex items-center justify-center rounded-full"><X size={18}/></button><div className="font-label text-gold text-xs tracking-[.24em] mb-3">{isUa?"ОКРЕМИЙ НАПРЯМ · QUALITY VISUALITY":"STANDALONE DIRECTION · QUALITY VISUALITY"}</div><h3 className="font-display text-4xl md:text-5xl text-[#f1ddb0] pr-10">{d.title}</h3><p className="font-body text-[#ddd8c9] leading-relaxed mt-4 max-w-2xl">{d.promise}</p><div className="gold-rule my-6"/><div className="font-label text-xs tracking-widest text-gold mb-3">{isUa?"ЯК ПРАЦЮЄМО":"HOW WE WORK"}</div><div className="grid sm:grid-cols-2 gap-3">{d.how.map((x,i)=><div key={i} className="tool-step"><CheckCircle2 size={16}/><span>{x}</span></div>)}</div><div className="tool-result-box"><Sparkles size={16}/><div><small>{isUa?"ЩО ОТРИМУЄШ":"WHAT YOU GET"}</small><p>{d.result}</p>{d.case&&<em>{isUa?"Приклад: ":"Example: "}{d.case}</em>}</div></div><div className="mt-7 flex flex-wrap gap-3 items-center"><a className="btn-gold inline-flex items-center gap-2 px-5 py-3 text-sm" href={`mailto:qualityvisuality@gmail.com?subject=${encodeURIComponent(`Quality Visuality · ${d.title}`)}`}><MessageCircle size={16}/>{isUa?"Написати мені":"Message me"}<ArrowRight size={16}/></a>{d.course&&<a className="btn-ghost inline-flex items-center gap-2 px-5 py-3 text-sm" href={`mailto:qualityvisuality@gmail.com?subject=${encodeURIComponent(`Quality Visuality · ${d.course}`)}`}><GraduationCap size={16}/>{isUa?"Дізнатись про курс":"Course details"}</a>}<a className="btn-ghost inline-flex items-center gap-2 px-5 py-3 text-sm" href="#courses" onClick={onClose}>{isUa?"Комплексний супровід":"Complete support"}<ArrowRight size={15}/></a><span className="text-dim text-xs w-full">{isUa?"Можна взяти лише цей напрям або включити його в комплексну систему. Ціну узгоджуємо після короткого брифу.":"Use only this direction or include it in complete support. Price is agreed after a short brief."}</span></div></div></div>
}
