// Procedural ambient engine: no external audio files, so every portal works immediately after a click.
// Chakra / Solfeggio numbers are used as artistic sound-design references, not medical claims.
export class AmbientAudio {
  constructor(){this.ctx=null;this.master=null;this.nodes=[];this.timers=[];this.current=null;this.enabled=true;this.noises={};}
  ensure(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=0;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume();}
  noise(kind='white'){if(this.noises[kind])return this.noises[kind];const len=this.ctx.sampleRate*2,b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<len;i++){const w=Math.random()*2-1;if(kind==='brown'){last=(last+.025*w)/1.025;d[i]=last*3.4}else if(kind==='pink'){last=.985*last+.12*w;d[i]=last*.55}else d[i]=w*.65;}this.noises[kind]=b;return b;}
  src(kind){const s=this.ctx.createBufferSource();s.buffer=this.noise(kind);s.loop=true;s.start();this.nodes.push(s);return s;}
  osc(freq,type='sine',gain=.05,out=this.master){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(out);o.start();this.nodes.push(o,g);return o;}
  tone(freq,gain=.1,decay=2,out=this.master){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+decay);o.connect(g);g.connect(out);o.start(t);o.stop(t+decay+.05);this.nodes.push(o,g);}
  bus(){const b=this.ctx.createGain();b.gain.value=1;b.connect(this.master);this.nodes.push(b);return b;}
  _water(out){const s=this.src('white'),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='lowpass';f.frequency.value=520;g.gain.value=.42;s.connect(f);f.connect(g);g.connect(out);this.osc(741,'sine',.018,out);const drip=()=>{if(this.current!=='water')return;this.tone(900+Math.random()*500,.055,.22,out)};this.timers.push(setInterval(drip,1250));}
  _wood(out){const s=this.src('pink'),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='bandpass';f.frequency.value=850;f.Q.value=.35;g.gain.value=.22;s.connect(f);f.connect(g);g.connect(out);this.osc(639,'sine',.022,out);const bird=()=>{if(this.current!=='wood')return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),gg=this.ctx.createGain();o.type='sine';const base=1700+Math.random()*1700;o.frequency.setValueAtTime(base,t);o.frequency.exponentialRampToValueAtTime(base*1.45,t+.08);gg.gain.setValueAtTime(.0001,t);gg.gain.exponentialRampToValueAtTime(.045,t+.02);gg.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(gg);gg.connect(out);o.start(t);o.stop(t+.16);this.nodes.push(o,gg)};this.timers.push(setInterval(bird,2100));}
  _fire(out){const s=this.src('brown'),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='lowpass';f.frequency.value=700;g.gain.value=.3;s.connect(f);f.connect(g);g.connect(out);[396,198,99].forEach((hz,i)=>this.osc(hz,'sine',.018/(i+1),out));const crack=()=>{if(this.current!=='fire')return;this.tone(700+Math.random()*1100,.025,.08,out)};this.timers.push(setInterval(crack,700));}
  _earth(out){const s=this.src('brown'),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='lowpass';f.frequency.value=180;g.gain.value=.28;s.connect(f);f.connect(g);g.connect(out);this.osc(174,'sine',.025,out);this.osc(87,'sine',.04,out);}
  _metal(out){const gong=()=>{if(this.current!=='metal')return;const t=this.ctx.currentTime;[1111,833.25,1666.5,555.5].forEach((hz,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.11/(i+1),t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+3.4-i*.35);o.connect(g);g.connect(out);o.start(t);o.stop(t+3.6);this.nodes.push(o,g)});};gong();this.timers.push(setInterval(gong,3400));this.osc(277.75,'sine',.025,out);}
  _brand(out){const s=this.src('pink'),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type='bandpass';f.frequency.value=900;f.Q.value=.5;g.gain.value=.06;s.connect(f);f.connect(g);g.connect(out);this.osc(936,'sine',.004,out);const city=()=>{if(this.current!=='brand')return;this.tone(900+Math.random()*300,.012,.08,out);if(Math.random()>.55)this.tone(1700+Math.random()*400,.018,.12,out)};this.timers.push(setInterval(city,850));}
  play(element){if(!this.enabled)return;this.ensure();this.stop(true);this.current=element;const out=this.bus();const map={water:'_water',wood:'_wood',fire:'_fire',earth:'_earth',metal:'_metal',brand:'_brand'};if(map[element])this[map[element]](out);const target=element==='brand'?.16:element==='earth'?.34:.26;this.master.gain.cancelScheduledValues(this.ctx.currentTime);this.master.gain.setValueAtTime(.0001,this.ctx.currentTime);this.master.gain.linearRampToValueAtTime(target,this.ctx.currentTime+.55);}
  stop(immediate=false){this.timers.forEach(clearInterval);this.timers=[];if(this.ctx&&this.master){this.master.gain.cancelScheduledValues(this.ctx.currentTime);this.master.gain.setValueAtTime(this.master.gain.value,this.ctx.currentTime);this.master.gain.linearRampToValueAtTime(0,this.ctx.currentTime+(immediate?.05:.35));}const old=this.nodes;this.nodes=[];setTimeout(()=>old.forEach(n=>{try{n.stop?.()}catch(e){}try{n.disconnect?.()}catch(e){}}),immediate?100:400);if(immediate)this.current=null;}
  toggle(v){this.enabled=v;if(!v)this.stop();}
}
export const ambient=new AmbientAudio();
