// Procedural sound design. Tones/frequencies are artistic references for the site's atmosphere,
// not claims about scientifically measured planetary frequencies or health effects.
export class AmbientAudio{
 constructor(){this.ctx=null;this.master=null;this.nodes=[];this.timers=[];this.current=null;this.enabled=true;this.noises={}}
 ensure(){if(typeof window==="undefined")return false;if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=.0001;this.master.connect(this.ctx.destination)}return true}
 noise(kind="white"){if(this.noises[kind])return this.noises[kind];const len=this.ctx.sampleRate*2,b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<len;i++){const w=Math.random()*2-1;if(kind==="brown"){last=(last+.025*w)/1.025;d[i]=last*3.4}else if(kind==="pink"){last=.985*last+.12*w;d[i]=last*.55}else d[i]=w*.65}this.noises[kind]=b;return b}
 src(kind){const s=this.ctx.createBufferSource();s.buffer=this.noise(kind);s.loop=true;s.start();this.nodes.push(s);return s}
 osc(freq,type="sine",gain=.05,out=this.master){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(out);o.start();this.nodes.push(o,g);return o}
 tone(freq,gain=.1,decay=2,out=this.master){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+decay);o.connect(g);g.connect(out);o.start(t);o.stop(t+decay+.05);this.nodes.push(o,g)}
 bus(){const b=this.ctx.createGain();b.gain.value=.8;b.connect(this.master);this.nodes.push(b);return b}
 water(out,base=741){const s=this.src("white"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=520;g.gain.value=.36;s.connect(f);f.connect(g);g.connect(out);this.osc(base,"sine",.018,out);const drip=()=>{if(this.current?.includes("water")||this.current==="neptune"||this.current==="earth")this.tone(900+Math.random()*500,.045,.22,out)};this.timers.push(setInterval(drip,1250))}
 natureWood(out){const s=this.src("pink"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="bandpass";f.frequency.value=850;f.Q.value=.35;g.gain.value=.18;s.connect(f);f.connect(g);this.osc(639,"sine",.022,out);const bird=()=>{if(!["wood","jupiter","uranus"].includes(this.current))return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),gg=this.ctx.createGain();o.type="sine";const b=1600+Math.random()*1800;o.frequency.setValueAtTime(b,t);o.frequency.exponentialRampToValueAtTime(b*1.4,t+.08);gg.gain.setValueAtTime(.0001,t);gg.gain.exponentialRampToValueAtTime(.04,t+.02);gg.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(gg);gg.connect(out);o.start(t);o.stop(t+.16);this.nodes.push(o,gg)};this.timers.push(setInterval(bird,2100))}
 fire(out,base=198){const s=this.src("brown"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=700;g.gain.value=.25;s.connect(f);f.connect(g);[base,base/2,base/4].forEach((hz,i)=>this.osc(hz,"sine",.018/(i+1),out));const crack=()=>{if(!["fire","mars","sun"].includes(this.current))return;this.tone(700+Math.random()*1100,.02,.08,out)};this.timers.push(setInterval(crack,700))}
 earth(out){const s=this.src("brown"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=180;g.gain.value=.22;s.connect(f);f.connect(g);this.osc(174,"sine",.025,out);this.osc(87,"sine",.035,out)}
 metal(out){const gong=()=>{if(!["metal","saturn","mercury"].includes(this.current))return;const t=this.ctx.currentTime;[1111,833.25,1666.5,555.5].forEach((hz,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type="sine";o.frequency.value=hz;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09/(i+1),t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+3.2-i*.3);o.connect(g);g.connect(out);o.start(t);o.stop(t+3.4);this.nodes.push(o,g)})};gong();this.timers.push(setInterval(gong,3400));this.osc(277.75,"sine",.025,out)}
 planet(id,out){const maps={sun:()=>{this.fire(out,220);this.osc(110,"sine",.018,out);this.osc(440,"triangle",.012,out)},mercury:()=>{this.metal(out);this.osc(880,"triangle",.012,out)},venus:()=>{this.osc(220,"sine",.028,out);this.osc(329.63,"sine",.018,out);this.osc(440,"sine",.01,out)},earth:()=>{this.water(out,396);this.natureWood(out)},mars:()=>{this.fire(out,110);this.osc(55,"triangle",.03,out)},jupiter:()=>{this.natureWood(out);this.osc(98,"sine",.045,out);this.osc(147,"sine",.018,out)},saturn:()=>this.metal(out),uranus:()=>{this.natureWood(out);this.osc(512,"sine",.014,out)},neptune:()=>this.water(out,432),pluto:()=>{this.earth(out);this.osc(41,"sine",.03,out)}};maps[id]?.()}
 brand(out){const s=this.src("pink"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="bandpass";f.frequency.value=900;f.Q.value=.5;g.gain.value=.05;s.connect(f);f.connect(g);this.osc(936,"sine",.004,out)}
 start(element){this.stop(true);this.current=element;const out=this.bus();const legacy={water:()=>this.water(out),wood:()=>this.natureWood(out),fire:()=>this.fire(out),earth:()=>this.earth(out),metal:()=>this.metal(out),brand:()=>this.brand(out)};if(legacy[element])legacy[element]();else this.planet(element,out);const target=element==="brand"?.16:(['earth','sun','jupiter'].includes(element)?.30:.24);const now=this.ctx.currentTime;this.master.gain.cancelScheduledValues(now);this.master.gain.setValueAtTime(.0001,now);this.master.gain.linearRampToValueAtTime(target,now+.18);return true}
 play(element){if(!this.enabled||!this.ensure())return false;const start=()=>{if(!this.enabled)return false;return this.start(element)};if(this.ctx.state==="running")return start();this.ctx.resume().then(start).catch(()=>{});return true}
 stop(immediate=false){this.timers.forEach(clearInterval);this.timers=[];if(this.ctx&&this.master){const now=this.ctx.currentTime;this.master.gain.cancelScheduledValues(now);this.master.gain.setValueAtTime(Math.max(this.master.gain.value,.0001),now);this.master.gain.linearRampToValueAtTime(.0001,now+(immediate?.03:.25))}const old=this.nodes;this.nodes=[];setTimeout(()=>old.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}),immediate?80:320);if(immediate)this.current=null}
 toggle(v){this.enabled=v;if(!v)this.stop()}
}
export const ambient=new AmbientAudio();
