// Procedural sound design. Frequency labels are an artistic symbolic mapping for atmosphere,
// not scientifically measured planetary frequencies or health/medical claims.
export class AmbientAudio{
 constructor(){this.ctx=null;this.master=null;this.nodes=[];this.timers=[];this.current=null;this.enabled=true;this.noises={}}
 ensure(){if(typeof window==="undefined")return false;if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=.0001;this.master.connect(this.ctx.destination)}return true}
 noise(kind="white"){if(this.noises[kind])return this.noises[kind];const len=this.ctx.sampleRate*2,b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<len;i++){const w=Math.random()*2-1;if(kind==="brown"){last=(last+.025*w)/1.025;d[i]=last*3.4}else if(kind==="pink"){last=.985*last+.12*w;d[i]=last*.55}else d[i]=w*.65}this.noises[kind]=b;return b}
 src(kind){const s=this.ctx.createBufferSource();s.buffer=this.noise(kind);s.loop=true;s.start();this.nodes.push(s);return s}
 osc(freq,type="sine",gain=.05,out=this.master){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(out);o.start();this.nodes.push(o,g);return o}
 tone(freq,gain=.1,decay=2,out=this.master){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+decay);o.connect(g);g.connect(out);o.start(t);o.stop(t+decay+.05);this.nodes.push(o,g)}
 bus(){const b=this.ctx.createGain();b.gain.value=.8;b.connect(this.master);this.nodes.push(b);return b}
 water(out,base=741){const s=this.src("white"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=520;g.gain.value=.34;s.connect(f);f.connect(g);g.connect(out);this.osc(base,"sine",.016,out);const drip=()=>{if(this.current==="water")this.tone(900+Math.random()*500,.04,.22,out)};this.timers.push(setInterval(drip,1300))}
 natureWood(out){const s=this.src("pink"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="bandpass";f.frequency.value=850;f.Q.value=.35;g.gain.value=.14;s.connect(f);f.connect(g);g.connect(out);this.osc(639,"sine",.018,out);const bird=()=>{if(this.current!=="wood")return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),gg=this.ctx.createGain();o.type="sine";const b=1600+Math.random()*1800;o.frequency.setValueAtTime(b,t);o.frequency.exponentialRampToValueAtTime(b*1.4,t+.08);gg.gain.setValueAtTime(.0001,t);gg.gain.exponentialRampToValueAtTime(.035,t+.02);gg.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(gg);gg.connect(out);o.start(t);o.stop(t+.16);this.nodes.push(o,gg)};this.timers.push(setInterval(bird,2300))}
 fire(out,base=528){const s=this.src("brown"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=700;g.gain.value=.18;s.connect(f);f.connect(g);g.connect(out);[base,base/2,base/4].forEach((hz,i)=>this.osc(hz,"sine",.016/(i+1),out));const crack=()=>{if(this.current!=="fire")return;this.tone(650+Math.random()*1200,.018,.08,out)};this.timers.push(setInterval(crack,760))}
 earth(out){const s=this.src("brown"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="lowpass";f.frequency.value=190;g.gain.value=.19;s.connect(f);f.connect(g);g.connect(out);this.osc(396,"sine",.014,out);this.osc(99,"sine",.03,out);this.osc(49.5,"sine",.035,out)}
 metal(out){const gong=()=>{if(this.current!=="metal")return;const t=this.ctx.currentTime;[852,426,1278,213].forEach((hz,i)=>{const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type="sine";o.frequency.value=hz;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.08/(i+1),t+.014);g.gain.exponentialRampToValueAtTime(.0001,t+3.4-i*.25);o.connect(g);g.connect(out);o.start(t);o.stop(t+3.6);this.nodes.push(o,g)})};gong();this.timers.push(setInterval(gong,3800));this.osc(284,"sine",.022,out)}
 brand(out){const s=this.src("pink"),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();f.type="bandpass";f.frequency.value=900;f.Q.value=.5;g.gain.value=.04;s.connect(f);f.connect(g);g.connect(out);this.osc(963,"sine",.0035,out)}
 start(element){this.stop(true);this.current=element;const out=this.bus();const map={water:()=>this.water(out),wood:()=>this.natureWood(out),fire:()=>this.fire(out),earth:()=>this.earth(out),metal:()=>this.metal(out),brand:()=>this.brand(out)};map[element]?.();this.tone(660,.018,.12,out);const target=element==="brand"?.12:element==="earth"?.28:.22;const now=this.ctx.currentTime;this.master.gain.cancelScheduledValues(now);this.master.gain.setValueAtTime(.0001,now);this.master.gain.linearRampToValueAtTime(target,now+.2);return true}
 play(element){if(!this.enabled||!this.ensure())return false;const start=()=>{if(!this.enabled)return false;return this.start(element)};if(this.ctx.state==="running")return start();this.ctx.resume().then(start).catch(()=>{});return true}
 stop(immediate=false){this.timers.forEach(clearInterval);this.timers=[];if(this.ctx&&this.master){const now=this.ctx.currentTime;this.master.gain.cancelScheduledValues(now);this.master.gain.setValueAtTime(Math.max(this.master.gain.value,.0001),now);this.master.gain.linearRampToValueAtTime(.0001,now+(immediate?.03:.25))}const old=this.nodes;this.nodes=[];setTimeout(()=>old.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}}),immediate?80:320);if(immediate)this.current=null}
 toggle(v){this.enabled=v;if(!v)this.stop()}
}
export const ambient=new AmbientAudio();
